config/routes.rb
Rails.application.routes.draw do
  
  mount Lockup::Engine, at: '/lockup'

  get 'timers/index'
  
  get '/for-teachers', to: 'static_pages#for_teachers'

  get '/about', to: 'static_pages#about'
  
  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
  patch '/newStory', to: 'timers#newStory'
  
  get '/contact', to: 'static_pages#contact'
  
  get '/inspiration', to: 'static_pages#inspiration'

  root 'static_pages#home'
  
  resources :timers
  resources :timer_mailers, only: [:edit]
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :content, presence: true
end

app/models/timer.rb
require 'digest/sha1'

class Timer < ApplicationRecord
  attr_accessor :remember_token
  before_save :process_input
  #regex allows for empty strings- maybe will fix later?
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z|\A\z/i
  validates :email, allow_nil: true, length: { maximum: 255 }, 
                                    format: { with: VALID_EMAIL_REGEX }
  
  def elapsed_time
    if !self.nil?
      self.time = (Time.now-self.created_at).floor
      self.time
    else
      0
    end
  end
  
  def Timer.digest(input)
    Digest::SHA1.hexdigest(input)
  end
  
  def Timer.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = Timer.new_token
    update_attribute(:remember_digest, Timer.digest(remember_token))
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  private
  
    def process_input
      if !email.blank?
        email.downcase!
      else
        self.email = nil
      end
    end
        
        
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  respond_to :js
  
  skip_before_action :check_for_lockup

  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    timer = Timer.find_by(id: params[:id])
    if timer
      log_in timer
      remember timer
      redirect_to timer
    else
      flash.now[:danger] = "Session create machine broke"
      redirect_to root_url
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  respond_to :html, :js
  
  def home
    if !session[:timer_id].nil?
      return redirect_to timer_path(session[:timer_id])
    end
  end

  def about
  end
  
  def for_teachers
  end
  
  def inspiration
  end
  
  def contact
  end
  
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :check_for_lockup
  
  def new
    @story = Story.new
  end
  
  def create
    @story = Story.new(story_params)
    
    if @story.save
      flash[:success] = "Story created!"
      redirect_to @story
    else
      flash.now[:danger] = "Story not created"
      render 'stories/new'
    end
  end
  
  def show
    @story = Story.find(params[:id])
  end
  
  def index
    @stories = Story.all
  end
  
  def edit
    @story = Story.find(params[:id])
  end
  
  def update
    @story = Story.find(params[:id])
    if @story.update_attributes(story_params)
      flash[:success] = "Profile updated"
      redirect_to @story
    else
      render 'edit'
    end
  end
  
  private

    def story_params
      params.require(:story).permit(:name, :img, :content)
    end
  
end

app/controllers/timer_mailers_controller.rb
class TimerMailersController < ApplicationController
  
  def edit
    timer = Timer.find(params[:id])
    if timer && !logged_in?
      log_in timer
      flash[:success] = "Successfully activated counter."
      redirect_to timer
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
    
  end
  
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  respond_to :html
  respond_to :js
  before_action :check_for_lockup, only: [:index]
  #resolve respond_to error
  
  def new
    @timer = Timer.new
  end
  
  def show
    @timer = Timer.find(params[:id])
    update_story
  end
  
  def index
    @timers = Timer.all
  end
  
  def create
    @timer = Timer.new(timer_params)
    
    if @timer.save
      log_in @timer
      if @timer.email.present?
        TimerMailer.log_in_code(@timer).deliver_now
      end
      flash[:success] = "Timer successfully created.#{" Check email for login link." if @timer.email.present? }"
      redirect_to @timer
    else
      render 'new'
    end
  end
  
  def destroy
    Timer.find(params[:id]).destroy
    flash[:success] = "Timer deleted"
    redirect_to timers_url
  end
  
  def newStory
    update_story
  end
  
  private
  
    def timer_params
      params.require(:timer).permit(:email)
    end
    
    def update_story
      if cookies[:story_num].nil?
        cookies[:story_num] = rand(Story.count)
      else
        cookies[:story_num] = ((cookies[:story_num].to_i + 1) % (Story.count)).to_s
      end
      # shift range from [0,Story.count-1] to [1, Story.count]
      @story = Story.find(cookies[:story_num].to_i + 1)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(object)
      if object.errors.any?
          content_tag(:div, class: "card border-danger") do
              concat(content_tag(:div, class: "card-header bg-danger text-white") do
                  concat "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
              end)
              concat(content_tag(:div, class: "card-body") do
                  concat(content_tag(:ul, class: 'mb-0') do
                      object.errors.full_messages.each do |msg|
                          concat content_tag(:li, msg)
                      end
                  end)
              end)
          end
      end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(timer)
    session[:timer_id] = timer.id
  end
  
  def current_timer
    if session[:timer_id]
      @current_timer ||= Timer.find_by(id: session[:timer_id])
    elsif cookies.signed[:timer_id]
      timer = Timer.find_by(id: cookies.signed[:timer_id])
      if timer
        log_in(timer)
        @current_timer = timer
      end
    end
  end
  
  def logged_in?
    !current_timer.nil?
  end
  
  def remember(timer)
    timer.remember
    cookies.permanent.signed[:timer_id] = timer.id
    cookies.permanent[:remember_token] = timer.remember_token
  end
  
  def forget(timer)
    timer.forget
    cookies.delete(:timer_id)
    cookies.delete(:remember_token)
    cookies.delete(:lockup)
  end
  
  def log_out
    forget(current_timer)
    session.delete(:timer_id)
    @current_timer = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/timer_mailers_helper.rb
module TimerMailersHelper
end

app/helpers/timers_helper.rb
module TimersHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <nav>
    <small>
      <ul class="list-unstyled">
        <li><%= link_to "Six Million Stories", '#'%></li>
      </ul>
    </small>
    <ul class="list-unstyled">
      <li><%= link_to "Inspiration", inspiration_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "For Teachers", for_teachers_path%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <%= link_to "Six Million Stories", root_path, id: "logo", class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if cookies[:lockup] %>
        <li class="nav-item"> <%= link_to "Timers", timers_index_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "New Story", new_story_path, class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Stories", stories_path, class: "nav-link" %></li>
      <% end %>
      <% if logged_in? %>
        <li class="nav-item"> <%= link_to "Reset Timer", '#', class: "nav-link" %></li>
        <li class="nav-item"> <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %></li>
      <% else %>
        <li class="nav-item"> <%= link_to "New Timer", new_timer_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SixMillionStories</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" type="text/css" href="https://rawgit.com/alvarotrigo/fullPage.js/master/jquery.fullPage.css" />
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'jquery_ujs.js' %>
    <%= javascript_include_tag 'https://rawgit.com/alvarotrigo/fullPage.js/master/jquery.fullPage.js' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if controller.action_name == "inspiration"%>
      <div class="container-fluid">
    <% else %>
      <div class="container">
    <% end %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <% if Rails.env.development? %>
        <div class="card">
          <div class="card-body">
            <%= debug(params) %>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/stories/_0.html.erb
<img class="img-fluid img-thumbnail visual img-responsive pull-left" src="https://www.holocaustcenterseattle.org/images/archive/photos/Gail.jpg"></img>

<h1>Gail Elad</h1> 

<p class="lead">Gail was born on October 10, 1940 in Warsaw, Poland, just six days before the establishment of the Warsaw Ghetto
Town was surrounded by walls and guards
Over 400,000 Jews were crammed into the ghetto at some point
Over 100,000 died in the ghetto due to the horrible conditions
Gail was smuggled out of the ghetto by her father in a duffel bag at the age of two, and her father hid her with a Polish family until the end of World War II
Gail’s mother died at a Nazi concentration camp
Gail lived in an orphanage with jewish orphans due to her dad’s work/dedication to saving the parentless children
In 1946, Gail arrived in the U.S. at Ellis Island, and started her new life
Grew up in California and became a teacher
Died of pancreatic cancer in 2008 
</p>

app/views/layouts/stories/_1.html.erb
<img class="img-fluid img-thumbnail visual img-responsive pull-left" src="https://www.holocaustcenterseattle.org/images/survivor-voices/images-HF/HF-3.jpg"></img>

<h1>Henry Friedman</h1> 

<p class="lead">  Born in 1928 in Brody, Poland
    In 1941, jews were forbidden to go to school, and were required to wear the star of David on their clothes
    If seen without the armband, jews would be beaten, including his mother
    The Friedman family was warned about the Gestapo coming for them, so they were able to flee in time. 
    In 1942, the family went into hiding with the help of two different Ukrainian families 
    The family hid in a small space in a barn owned by the family of Julia Symchuck for 18 months
    The friedmans were freezing and slowly starved for those 18 months.
    Were liberated in March 1944 by the Russians</p>

app/views/layouts/stories/_2.html.erb
<h1>Martin Kapel</h1>

<p class="lead">Martin was born in Leipzig, Germany in 1930 and was legally classed as a Polish citizen by the nationality laws of both Poland and Germany 
Martin was brought up in an orthodox Jewish household 
Martin began going to school shortly before his sixth birthday and by his time the Nazis were already in power and Martin recalls the Nazi propaganda that formed part of his education 
In 1938, Jewish children were no longer allowed to go to non-Jewish schools 
One morning in 1938 Martin and his family were asleep in their beds when there was a knock at the door, Nazis walked in and the family were told to dress quickly and go with them
Only allowed to take what they could grab on the spur of the moment and were watched carefully to ensure they didn't try to take any valuables
They were taken to a small police station and eventually a bus arrived and they got on the bus and were taken to a railway station to join a large crowd of people
Everyone was put on a train, and a short distance into the journey some of the passengers realised they were locked in and could not open the train door from the inside
SS men and German police on the platform threatened to shoot anyone who tried to escape.
After dark, the train arrived at a small railway station and everyone was ordered to get off.
The prisoners were formed into rows, with an SS man at the end of each row, and marched off past a small town and into a forest 
Eventually the column was stopped beside a railway line and the people were told that the SS men would go no further but that they should continue and walk along the railway line between the rails
They walked for hours in the dark along the railway line, with a number of people tripping and being trampled by those behind who couldn't see where they were going
After a few hours some Polish police and soldiers arrived and they realised that they were in Poland
The expulsion had been carried out in secret by the Germans so the Polish authorities had no idea that it was happening(Polenaktion)
Martin and his mother and sister managed to get away and eventually made their way to some relations in Krakow
They stayed with their relatives until they were able to find somewhere else to stay and were in Krakow for about eight months
They were welcomed by their relatives but not by the Polish authorities, who considered them to be illegal immigrants
After eight months in Krakow, Martin and his family went to stay with other relatives in a small village called Brzesko 
Martin's mother managed to get Martin and his sister a place on the Kindertransport that was arranged for those children who had been involved in the forced expulsion from Germany
They travelled to England and went to live with foster parents in Coventry and were met there by their new foster-mother and arrived in Coventry by train in the early evening.
Martin describes being anxious and very much afraid
</p>

app/views/layouts/stories/template.html.erb
<img class="img-fluid img-thumbnail visual img-responsive pull-left" src="https://www.placehold.it/400x400"></img>

<h1>Name</h1> 

<p class="lead">Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown
printer took a galley of type and scrambled it to make a type specimen book. 
It has survived not only five centuries, but also the leap into electronic typesetting, 
remaining essentially unchanged. It was popularised in the 1960s with the release of 
Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy 
text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard 
dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled 
it to make a type specimen book. It has survived not only five centuries, but also the leap 
into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s 
with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with 
desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem 
Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been 
the industry's standard dummy text ever since the 1500s, when an unknown printer took a 
galley of type and scrambled it to make a type specimen book. It has survived not only 
five centuries, but also the leap into electronic typesetting, remaining essentially 
unchanged. It was popularised in the 1960s with the release of Letraset sheets containing 
Lorem Ipsum passages, and more recently with desktop publishing software like Aldus 
PageMaker including versions of Lorem Ipsum.</p>

app/views/shared/_error_messages.html.erb
<% if @timer.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger" role="alert">
      The form contains <%= pluralize(@timer.errors.count, "error") %>.
    </div>
    <ul>
    <% @timer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About</h1>

<div class="page-content">
  
  <h3>The Problem</h3>
  
  <p class="lead">
    Often times, when dealing with issues of mass tragedies in faraway lands from
    long ago ages, large numbers with many zeros are referenced when referring
    to the people of these events. <b>It can be all too easy to see these numbers
    and not take the time to process them.</b> When referring to human tragedies,
    the difference in perception between 5 deaths and 10 deaths seems massive,
    while the difference between 6,000,000 and 6,000,005 seems negligible.
    In reality, <b>each one of these deaths is a human life, and deserves to be
    treated as such.</b>
  </p>
  
  <h3>Our Goal</h3>
  
  <p class="lead">
    With our application, we hope to allow users to begin to <b>comprehend the huge
    numbers often referenced when referring to mass tragedies</b>, specifically the
    holocaust, by creating a visualization of the . We find it to be extremely important to recognize and value the
    <b>individuality of every life lost</b>, something we hope for our users to achieve
    through the visualization this site provides.
  </p>
  
  <h3>Usage</h3>
  
  <p class="lead">
    The user can create their own counter, which will count every second, even when
    the user is not present. They have the option to enter an email, where they will
    be emailed a link to retrieve their counter if they accidentally log out.
  </p>
</div>

app/views/static_pages/for_teachers.html.erb
<h1>For Teachers</h1>

<h3>Our Purpose</h3>
<p class="lead">
  An an application that visualizes the enormity of the number of deaths reported
  in mass tragedies, specifically the holocaust, by recognizing that within
  every singular digit in these large numbers is the story of a human being.
</p>

<h3>Potential Uses in the Classroom</h3>

<div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel">

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

        <!--First slide-->
        <div class="carousel-item active">
          <div class="card">
            <h5 class="card-header">Usage One</h5>
            <div class="card-body">
              <h5 class="card-title">Unit-Based Application</h5>
              <p class="card-text">
                The teacher could begin a new timer at the beginning of a <b>unit
                on WWII, the holocaust, Night by Elie Wiesel,</b> or another topic
                which relates to these themes. The teacher could then discuss with
                the students what each number represents, and the importance of
                recognizing the individuality of victims. The teacher could check
                in periodically with the counter, having kids guess how big the
                number has become, <b>demonstrating the immensity of the number 
                6 million.</b>
              </p>
            </div>
          </div>
        </div>
        <!--/.First slide-->

        <!--Second slide-->
        <div class="carousel-item">
          <div class="card">
            <h5 class="card-header">Usage Two</h5>
            <div class="card-body">
              <h5 class="card-title">Use for the stories</h5>
              <p class="card-text">
                If students all have personal access to the site, you could allow
                them to <b>explore the stories,</b> helping them learn about
                the individual lives lost in the holocaust.
              </p>
            </div>
          </div>
        </div>
        <!--/.Second slide-->

        <!--Third slide-->
        <div class="carousel-item">
          <div class="card">
            <h5 class="card-header">Usage Three</h5>
            <div class="card-body">
              <h5 class="card-title">Interactive Usage</h5>
              <p class="card-text">
                The teacher can <b>share the link which was sent by email</b> upon sign
                up with the students, who would then have access to the counter
                and would be able to <b>view it at home or in class.</b>
              </p>
            </div>
          </div>
        </div>
        <!--/.Third slide-->

    </div>
    <!--/.Slides-->
    
    <div class="controls-top">
      <a class="carousel-control-prev btn-floating" href="#multi-item-example" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#multi-item-example" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
</div>
<!--/.Carousel Wrapper-->

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  
  <body>
    
    <div class="center jumbotron">
      <h1>Six Million Stories</h1>
      <!-- <blockquote class="blockquote">
        <p>"The death of one man is a tragedy, the death of millions is a statistic."</p>
        <footer class="blockquote-footer"><cite title="Source Title">Joseph Stalin</cite></footer>
      </blockquote> -->
      <h2>
        An an application that visualizes the enormity of the number of deaths reported
        in mass tragedies, specifically the holocaust, by recognizing that within
        every singular digit in these large numbers is the story of a human being.
      </h2>
      <% if cookies[:lockup] %>
        <div style="text-align:center;">
          <%= button_to 'Timers', timers_index_path, method: :get, class: "btn btn-primary" %>
        </div>
      <% else %>
        <div class="wrapper text-center">
          <h6>
            Begin your experience by creating a new counter, or by learning more
            about the site:
          </h6>
          <div class="btn-group">
            <%= button_to 'For Teachers', for_teachers_path, method: :get, class: "btn btn-primary"%>
            <%= button_to 'New Counter', new_timer_path, method: :get, class: "btn btn-primary"%>
            <%= button_to 'About', about_path, method: :get, class: "btn btn-primary"%>
          </div>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<div class="wrapper">
  <%= form_for @story, :html => {:class => "story-form"} do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :img, class: "control-label" %>
      <%= f.text_field :img, class: "form-control" %>
      <small id="nameHelpBlock" class="form-text text-muted">
        Optional: enter link to relating image
      </small>
      
      <%= f.label :content, class: "control-label" %>
      <%= f.text_area :content, class: "form-control" %>
    </div>


    <%= f.submit "Save Changes", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/stories/index.html.erb
<h1>Stories</h1>

<ul class="object-index">
  <% @stories.each do |story| %>
    <li class="object-item">
      <%= link_to "Story #{story.id}", story_path(story), class: "btn btn-secondary" %> : <%= story.name %>
      | <%= link_to "delete", story, method: :delete, data: {confirm: "You sure?"} %>
      | <%= link_to "edit", edit_story_path(story)%>
    </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<h1>New Story</h1>

<div class="wrapper">
  <%= form_for @story, :html => {:class => "input-form"} do |f| %>
    <div class="form-group">
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :img, class: "control-label" %>
      <%= f.text_field :img, class: "form-control" %>
      <small id="nameHelpBlock" class="form-text text-muted">
        Optional: enter link to relating image
      </small>
      
      <%= f.label :content, class: "control-label" %>
      <%= f.text_area :content, class: "form-control" %>
    </div>


    <%= f.submit "Create story", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/stories/show.html.erb
<h1>Story Preview</h1>

<div style="text-align:center;">
  <%= button_to 'Edit', edit_story_path(@story), method: :get, class: "btn btn-primary" %>
</div>

<div class="container">
  <div class="box">
    <div class="row row-one">
      <div class="col-md-12 imageholder">
        <% if @story.img.present? %>
          <img class="img-fluid img-thumbnail visual img-responsive pull-left" src=<%= @story.img %>></img>
        <% end %>
        
        <h1><%= @story.name %></h1></h1> 
        
        <p class="lead"><%= @story.content %></p>
      </div>
    </div>
  </div>
</div>
  

app/views/timers/_story.html.erb
<div class="container">
  <div class="box">
    <div class="row row-one">
      <div class="col-md-12 imageholder">
        <% if @story.img.present? %>
          <img class="img-fluid img-thumbnail visual img-responsive pull-left" src=<%= @story.img %>></img>
        <% end %>
        
        <h1><%= @story.name %></h1></h1> 
        
        <p class="lead"><%= @story.content %></p>
      </div>
    </div>
  </div>
</div>

app/views/timers/index.html.erb
<h1>Timers</h1>

<ul class="object-index">
  <% @timers.each do |timer| %>
    <li class="object-item">
      <%= link_to "Timer #{timer.id}", timer_path(timer), class: "btn btn-secondary" %> : <%= timer.elapsed_time %>
      | <%= link_to "delete", timer, method: :delete, data: {confirm: "You sure?"} %>
      | <%= link_to "log in as", login_path(id: timer.id), method: :post%>
    </li>
  <% end %>
</ul>

app/views/timers/new.html.erb
<h1>
  New Counter
</h1>
<div class="wrapper">
  
  <%= form_for @timer, :html => {:class => "input-form"} do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="form-group">
      <%= f.label :email, class: "control-label" %>
      <%= f.email_field :email, class: "form-control" %>
      <small id="passwordHelpBlock" class="form-text text-muted">
        Optional: enter email where you can recover your timer
      </small>
    </div>


    <%= f.submit "Create counter", class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/timers/newStory.js.erb
$("#story").html("<%= j render(partial: 'story') %>");

app/views/timers/show.html.erb
<head>
  <script>
    var myVar = setInterval(myTimer, 1000);
    var time = <%= @timer.elapsed_time %>
    function myTimer() {
      document.querySelector("clock").innerHTML = time;
      time++;
    }
  </script>
</head>

<div class="container show-body">
  <div id='counter'>
    <h2><clock><%= @timer.elapsed_time %></clock></h2>
  </div>
  
  <hr>
  
  <div id="story">
    <%= render 'story' %>
  </div>
  
  <div id="new-story-button">
    <%= button_to 'New Story', newStory_path, method: :patch, remote: true, class: "btn btn-primary" %>
  </div>
  
  
</div>